// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFKUj8tyUxjaV5INhoNkrCdJqSoVcyqM',
    appId: '1:252405280358:web:2ffef1a9460d08298b07a7',
    messagingSenderId: '252405280358',
    projectId: 'glicnote-df11f',
    authDomain: 'glicnote-df11f.firebaseapp.com',
    storageBucket: 'glicnote-df11f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2TMKeRQIksbRIok4w7Te0N-SKAh55BA',
    appId: '1:252405280358:android:95b79ebb731a2dce8b07a7',
    messagingSenderId: '252405280358',
    projectId: 'glicnote-df11f',
    storageBucket: 'glicnote-df11f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSdlSCqxYwUwSnFZiDVVlOlMiTYlldkUE',
    appId: '1:252405280358:ios:e263345eb94affca8b07a7',
    messagingSenderId: '252405280358',
    projectId: 'glicnote-df11f',
    storageBucket: 'glicnote-df11f.firebasestorage.app',
    iosBundleId: 'com.example.glicNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSdlSCqxYwUwSnFZiDVVlOlMiTYlldkUE',
    appId: '1:252405280358:ios:e263345eb94affca8b07a7',
    messagingSenderId: '252405280358',
    projectId: 'glicnote-df11f',
    storageBucket: 'glicnote-df11f.firebasestorage.app',
    iosBundleId: 'com.example.glicNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPFKUj8tyUxjaV5INhoNkrCdJqSoVcyqM',
    appId: '1:252405280358:web:c506e887946c602b8b07a7',
    messagingSenderId: '252405280358',
    projectId: 'glicnote-df11f',
    authDomain: 'glicnote-df11f.firebaseapp.com',
    storageBucket: 'glicnote-df11f.firebasestorage.app',
  );
}
